### ISSUE TITLE
After installing plastex: Script 'scripts/plastex' not found in metadata at 

### ISSUE THREAD

**Issue by skinkie** [plastex/plastex#266]
```
skinkie@thinkpad ~/Sources/plastex $ plastex 
Traceback (most recent call last):
  File "/usr/bin/plastex", line 4, in <module>
    __import__('pkg_resources').run_script('plasTeX==2.1', 'plastex')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1436, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/plastex' not found in metadata at '/mnt/storage/home/skinkie/.local/lib/python3.9/site-packages/plasTeX-2.1-py3.9.egg-info'
```

**Comment by PatrickMassot** [comment]
This should be fixed in the latest release.
