### ISSUE TITLE
UnicodeDecodeError: invalid start byte

### ISSUE THREAD

**Issue by shmup** [plastex/plastex#294]
I see a similar issue here: https://github.com/plastex/plastex/issues/106

Here's where I opened the issue, before I figured this is a good place to open it:

https://github.com/warsus/lions-/issues/4

The error:

```
 File "/usr/lib64/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 3825: invalid start byte
```

Here's a full dump:

```
~/src/lions (gh-pages *%)$ make
plastex --save-image-file --imager="gsdvipng" -d ./lionc lionstex/lionc.tex
plasTeX version 2.1
 (loading package /home/jtm/.local/lib/python3.10/site-
   packages/plasTeX/Packages/article.py
 )
WARNING: unrecognized command/environment: font
WARNING: unrecognized command/environment: twlrm
......
WARNING: unrecognized command/environment: rhead
WARNING: unrecognized command/environment: leftmark
WARNING: unrecognized command/environment: lhead
WARNING: unrecognized command/environment: chead
WARNING: unrecognized command/environment: lfoot
WARNING: unrecognized command/environment: cfoot
WARNING: unrecognized command/environment: rfoot
. ( ./lionstex/title.tex )........... ( ./lionstex/preface.tex )...........
.....................................................................
 ( ./lionstex/ch1.tex )....................................................
...........................................................................
......................... ( ./lionstex/ch2.tex )...........................
...........................................................................
...........................................................................
...........................................................................
.................................................. ( ./lionstex/ch3.tex )..
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...........................................................................
...... ( ./lionstex/ch4.tex )..............................................
...........................................................................
...........................................................................
.... ( ./lionstex/ch5.tex )................................................
...........................................................................
...........................................................................
...........................................................................
.......................... ( ./lionstex/ch6.tex )..........................
...........................................................................
...........................................................................
...........................................................................
................. ( ./lionstex/ch7.tex )...................................
...........................................................................
...........................................................................
...........................................................................
.......... ( ./lionstex/ch8.tex )..........................................
...........................................................................
...........................................................................
...................... ( ./lionstex/ch9.tex )..............................
...........................................................................
........ ( ./lionstex/ch10.tex )...........................................
...........................................................................
...........................................................
 ( ./lionstex/ch11.tex )...................................................
............................................. ( ./lionstex/ch12.tex )
ERROR: An error occurred while building the document object in
   ./lionstex/ch12.tex on line 1 ('utf-8' codec can't decode byte 0xa3 in
   position 3825: invalid start byte)
Traceback (most recent call last):
  File "/usr/local/bin/plastex", line 73, in <module>
    main(sys.argv)
  File "/usr/local/bin/plastex", line 53, in main
    run(filename, config)
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/Compile.py", line 90, in run
    tex = parse(filename, config)
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/Compile.py", line 85, in parse
    tex.parse()
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/TeX.py", line 415, in parse
    item.digest(tokens)
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/__init__.py", line 926, in digest
    item.digest(tokens)
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/Base/LaTeX/Sectioning.py", line 286, in digest
    item.digest(tokens)
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/Base/LaTeX/Sectioning.py", line 277, in digest
    for item in tokens:
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/TeX.py", line 43, in __next__
    return self._next()
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/TeX.py", line 298, in __iter__
    token = next()
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/TeX.py", line 266, in itertokens
    t = next(inputs[-1][-1])
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/Tokenizer.py", line 370, in __iter__
    (code, char) = next(charIter)
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/Tokenizer.py", line 264, in iterchars
    token = _read1()
  File "/home/jtm/.local/lib/python3.10/site-packages/plasTeX/Tokenizer.py", line 261, in _read1
    return read(1)
  File "/usr/lib64/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 3825: invalid start byte
make: *** [Makefile:2: lions] Error 1
```

**Comment by shmup** [comment]
Already answered elsewhere, and fixed by author
