### ISSUE TITLE
Failing natbib test

### ISSUE THREAD

**Issue by PatrickMassot** [plastex/plastex#70]
Trying to update functional tests, I stumbled upon what looks like an actual regression (in master branch).
Steps to reproduce:
* copy ``unittests/Packages/sources/natbib.tex`` and ``unittests/Packages/extras/natbib.bib`` in some new directory
* in this directory, run ``pdflatex natib.tex``, ``bibtex natib``, ``pdflatex natib.tex``, ``pdflatex natib.tex`` to create the following natbib.bbl:
```latex
\begin{thebibliography}{2}
\providecommand{\natexlab}[1]{#1}
\providecommand{\url}[1]{\texttt{#1}}
\expandafter\ifx\csname urlstyle\endcsname\relax
  \providecommand{\doi}[1]{doi: #1}\else
  \providecommand{\doi}{doi: \begingroup \urlstyle{rm}\Url}\fi

\bibitem[Hagen(2000)]{hagen:metafun}
Hans Hagen.
\newblock Metafun.
\newblock Preliminary Version October 27, 2000, October 2000.
\newblock \texttt{http://www.pragma-ade.com}.

\bibitem[von Goossens et~al.(1997)von Goossens, Rahtz, and
  Mittelbach]{goossens:companion}
M.~von Goossens, S.~Rahtz, and F.~Mittelbach.
\newblock \emph{The LaTeX Graphics Companion}.
\newblock Addison-Wesley Publishing Company, Reading, Mass., 1997.

\end{thebibliography}
```
* run ``plastex natibib.tex`` to see:
```
ERROR: Error while expanding "ifx" in ./natbib.bbl on line 4 ('urlstyle'
   object has no attribute 'catcode')
ERROR: An error occurred while building the document object in ./natbib.bbl
   on line 4 ('urlstyle' object has no attribute 'catcode')
Traceback (most recent call last):
  File ".virtualenvs/plastex/bin/plastex", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "plastex/plasTeX/plastex", line 128, in <module>
    main(sys.argv)
  File "plastex/plasTeX/plastex", line 73, in main
    tex.parse()
  File "plastex/plasTeX/TeX.py", line 434, in parse
    item.digest(tokens)
  File "plastex/plasTeX/__init__.py", line 904, in digest
    item.digest(tokens)
  File "plastex/plasTeX/Base/LaTeX/Sectioning.py", line 294, in digest
    item.digest(tokens)
  File "plastex/plasTeX/Base/LaTeX/Bibliography.py", line 79, in digest
    for tok in tokens:
  File "plastex/plasTeX/TeX.py", line 46, in next
    return self._next()
  File "plastex/plasTeX/TeX.py", line 340, in __iter__
    tokens = obj.invoke(self)
  File "plastex/plasTeX/Base/TeX/Primitives.py", line 282, in invoke
    self.parse(tex)
  File "plastex/plasTeX/__init__.py", line 476, in parse
    **arg.options)
  File "plastex/plasTeX/TeX.py", line 688, in readArgumentAndSource
    if t.catcode == Token.CC_BGROUP:
AttributeError: 'urlstyle' object has no attribute 'catcode'
```

**Comment by kesmit13** [comment]
I'm not sure if this is a regression, or if bibtex is now generating more code than it used to.  Looking at that `\expandafter\ifx` code, I'd be impressed if plasTeX could make it through that.  I'm going to have to think about how to handle this one.
